[2024-11-07T15:01:29.547+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-11-07T15:01:29.559+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.run_etl scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T15:01:29.568+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.run_etl scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T15:01:29.568+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-07T15:01:29.582+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): run_etl> on 2024-11-06 00:00:00+00:00
[2024-11-07T15:01:29.589+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2024-11-07T15:01:29.594+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'run_etl', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpo6lntf8a']
[2024-11-07T15:01:29.597+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask run_etl
[2024-11-07T15:01:29.624+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-07T15:01:29.673+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_etl.run_etl scheduled__2024-11-06T00:00:00+00:00 [running]> on host 1e4604ed6e37
[2024-11-07T15:01:29.689+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-11-07T15:01:30.062+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-06T00:00:00+00:00'
[2024-11-07T15:01:30.326+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_etl_dag.py", line 36, in etl_workflow
    df = transform_data(data)
  File "/opt/airflow/dags/scripts/transform.py", line 2, in transform_data
    df = pd.DataFrame([data], columns=['city', 'temperature', 'humidity', 'weather'])
NameError: name 'pd' is not defined
[2024-11-07T15:01:30.334+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_etl, task_id=run_etl, execution_date=20241106T000000, start_date=20241107T150129, end_date=20241107T150130
[2024-11-07T15:01:30.346+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2 for task run_etl (name 'pd' is not defined; 57)
[2024-11-07T15:01:30.384+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-11-07T15:01:30.400+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
