[2024-11-13T14:43:16.302+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-11-13T14:43:16.316+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.load scheduled__2024-11-12T00:00:00+00:00 [queued]>
[2024-11-13T14:43:16.325+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.load scheduled__2024-11-12T00:00:00+00:00 [queued]>
[2024-11-13T14:43:16.326+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-11-13T14:43:16.339+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load> on 2024-11-12 00:00:00+00:00
[2024-11-13T14:43:16.343+0000] {standard_task_runner.py:57} INFO - Started process 71 to run task
[2024-11-13T14:43:16.347+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'load', 'scheduled__2024-11-12T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp_gaexu45']
[2024-11-13T14:43:16.349+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask load
[2024-11-13T14:43:16.360+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-13T14:43:16.397+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_etl.load scheduled__2024-11-12T00:00:00+00:00 [running]> on host 4d6a8824ba23
[2024-11-13T14:43:16.407+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-11-13T14:43:16.698+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-12T00:00:00+00:00'
[2024-11-13T14:43:16.760+0000] {logging_mixin.py:149} INFO - Ошибка при загрузке данных в базу данных: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(weather_data, 2200) already exists.

[SQL: 
CREATE TABLE weather_data (
	city TEXT, 
	temperature FLOAT(53), 
	humidity BIGINT, 
	weather TEXT, 
	retrived_at TIMESTAMP WITHOUT TIME ZONE
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-11-13T14:43:16.761+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-13T14:43:16.769+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=load, execution_date=20241112T000000, start_date=20241113T144316, end_date=20241113T144316
[2024-11-13T14:43:16.815+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-11-13T14:43:16.840+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
